### PR TITLE
Independent control of text and number size + documentation updates

### PR DESCRIPTION
**Pull request by joshhartman**
Great job on this plugin. I've added a feature that I think is necessary when using small (~300px wide) countdown timers.

### CODE REVIEW

**Comment by wimbarelds** [comment]
Hey there, thanks for the updates! Any chance you could link to a place where you demo these changes? I'm currently moving into a new house; so unfortunately don't have a lot of time. These changes however look good on the surface, would just like to quickly see them in action one time.

One change that does seem out of place in the documentation (though mind you, English is my second language); the "it self" vs "its self"; to me it seems "it self" would be correct. Might be wrong of course, the rest all looked good.

**Comment by qrahaman** [comment]
And it should be one word, as in, “itself”.

**Comment by joshhartman** [comment]
Here is my specific use case:

https://www.netdev.us/joshhartman/timecircles.html

And here are links for comparison with your example page.

http://www.netdev.us/joshhartman/TimeCircles-master/
http://www.netdev.us/wimbarelds/TimeCircles-master/

You may want the `number_size` default to be `0.21` to match your sizing in the examples.

I also see that the repository example pages can't be loaded over HTTPS because the link to jQuery is non-secure. Also, the script works fine on jQuery v2.x.

@qrahaman Thanks, I knew it wasn't "it self" and needed to show possession.

**Comment by joshhartman** [comment]
Darn, why do they put the close request button next to comment?

Anyways, here is a comparison page using your code base:

https://www.netdev.us/wimbarelds/timecircles.html

Not a big difference but it's all about flexibility and legibility for small countdown timers.

**Comment by wimbarelds** [comment]
Thanks! I'll merge this in and add it to the download sometime later; hoping ill have more free time soon.

**Pull request merged**
